global:
  namespace: microservices
# Configuración del ConfigMap
config:
  authApiPort: "8081"
  usersApiAddress: "http://microservices-users-api-svc.microservices.svc.cluster.local:8083"
# Configuración de la imagen
image:
  repository: acrdevmicroservices2026.azurecr.io/auth-api
  tag: "v1.0.2"
  pullPolicy: IfNotPresent
# Configuración del servicio
service:
  type: ClusterIP
  port: 8081
# Recursos del contenedor
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
# Réplicas
replicaCount: 1
# HPA configuración
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
# Labels
labels:
  app: auth-api
#Linkerd annotations
annotations:
  linkerd.io/inject: enabled
  
#ServiceProfile configuration for Linkerd
serviceProfile:
  timeout: 5s
  isRetryable: true
  pathRegex: ".*"
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s