# Denegar todo el trafico.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: microservices
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

# Permitir trafico interno entre los microservicios.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: microservices
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: microservices

# Permitir el trafico desde el gateway hacia los microservicios.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-gateway
  namespace: microservices
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: gateway-infra
# Permitir trafico de entrada para DNS y asi resolver nombres internos
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: microservices
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
#Negar todo el trafico en el namespace de infra.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: gateway-infra
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
#Permitir el trafico externo
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-ingress
  namespace: gateway-infra
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - {}
# Permitiendo la comunicacion con los servicios
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-microservices
  namespace: gateway-infra
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: microservices
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
# Denegar trafico en el frontend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: frontend
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
# Permitir trafico externo al frontend
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-ingress
  namespace: frontend
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - {}
# Permitir que el frontend se comunique con el gateway
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-gateway
  namespace: frontend
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: gateway-infra
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP