# Configuración global
global:
  namespace: microservices
config:
  # Puerto del servidor
  serverPort: "8083"
# Configuración de la imagen
image:
  repository: acrdevmicroservices2026.azurecr.io/users-api
  tag: "v1.0.3"
  pullPolicy: IfNotPresent
# Configuración del servicio
service:
  type: ClusterIP
  port: 8083
# Recursos del contenedor
resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "750Mi"
    cpu: "500m"
# Réplicas
replicaCount: 1
# HPA configuración
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
# Labels
labels:
  app: users-api
#Linkerd annotations
annotations:
  linkerd.io/inject: enabled
#ServiceProfile configuration for Linkerd
serviceProfile:
  timeout: 5s
  isRetryable: true
  pathRegex: ".*"
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s
