apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s-config" .Release.Name .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.labels.app }}
data:
  AUTH_API_PORT: {{ .Values.config.authApiPort | quote }}
  USERS_API_ADDRESS: {{ .Values.config.usersApiAddress | quote }}