apiVersion: v1
kind: ConfigMap
metadata:
  # CAMBIO: Usamos Release.Name
  name: {{ printf "%s-%s-config" .Release.Name .Chart.Name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: {{ .Values.labels.app | quote }}
data:
  TODO_API_PORT: {{ .Values.config.todoApiPort | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  REDIS_CHANNEL: {{ .Values.config.redisChannel | quote }}