apiVersion: v2
name: microservice-app
description: A Helm chart for the Microservices Application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: auth-api
    version: 0.1.0
    repository: "file://charts/auth-api"

  - name: todos-api
    version: 0.1.0
    repository: "file://charts/todos-api"

  - name: users-api
    version: 0.1.0
    repository: "file://charts/users-api"

  - name: log-message-processor
    version: 0.1.0
    repository: "file://charts/log-message-processor"