# Configuración para ambiente DEV

# Configuración global para todos los subcharts
global:
  namespace: microservices-dev

# Configuración específica para auth-api
auth-api:
  replicaCount: 1
  global:
    namespace: microservices-dev
  image:
    tag: "1.0.0"

# Configuración específica para todos-api
todos-api:
  replicaCount: 1
  global:
    namespace: microservices-dev
  image:
    tag: "1.0.0"
  config:
    redisHost: "redis-master"

# Configuración específica para users-api
users-api:
  replicaCount: 1
  global:
    namespace: microservices-dev
  image:
    tag: "1.0.0"
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "768Mi"
      cpu: "500m"

# Configuración específica para log-message-processor
log-message-processor:
  replicaCount: 1
  global:
    namespace: microservices-dev
  image:
    tag: "1.0.0"
  config:
    redisHost: "redis-master"