# Configuración para ambiente PROD

# Configuración global para todos los subcharts
global:
  namespace: microservices-prod

# Configuración específica para auth-api
auth-api:
  replicaCount: 3
  global:
    namespace: microservices-prod
  image:
    tag: prod

# Configuración específica para todos-api
todos-api:
  replicaCount: 3
  global:
    namespace: microservices-prod
  image:
    tag: prod

# Configuración específica para users-api
users-api:
  replicaCount: 3
  global:
    namespace: microservices-prod
  image:
    tag: prod

# Configuración específica para log-message-processor
log-message-processor:
  replicaCount: 3
  global:
    namespace: microservices-prod
  image:
    tag: prod