apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-azure-dns
spec:
  acme:
    email: shernandezsaavedra2004@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        cnameStrategy: Follow
        azureDNS:
          resourceGroup: rg-dev-microservices-eastus2
          subscriptionID: ${AZURE_SUBSCRIPTION_ID}
          hostedZoneName: certs.santiago.monster
          environment: AzurePublicCloud
          managedIdentity:
            clientID: ${AKS_MANAGED_IDENTITY_CLIENT_ID}
