apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  # CAMBIO: El nombre debe coincidir con el FQDN del nuevo Service
  name: {{ printf "%s-%s-svc.%s.svc.cluster.local" .Release.Name .Chart.Name .Values.global.namespace | quote }}
  namespace: {{ .Values.global.namespace | quote }}
spec:
  routes:
    - name: all routes
      condition:
        pathRegex: {{ .Values.serviceProfile.pathRegex | quote }}
      timeout: {{ .Values.serviceProfile.timeout }}
      isRetryable: {{ .Values.serviceProfile.isRetryable }}
  retryBudget:
    retryRatio: {{ .Values.serviceProfile.retryBudget.retryRatio }}
    minRetriesPerSecond: {{ .Values.serviceProfile.retryBudget.minRetriesPerSecond }}
    ttl: {{ .Values.serviceProfile.retryBudget.ttl }}