global:
  
  targetNamespace: microservices
  
  litmusNamespace: litmus
  
  prometheusEndpoint: "http://monitoring-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
 

experiments:
  podDelete:
    enabled: true
    
    appLabel: "auth-api"
    appNamespace: microservices
    
    totalChaosDuration: 30      
    chaosInterval: 10           
    force: false                
    
    probeUrl: "http://frontend-frontend-aut-aks-svc.frontend.svc.cluster.local:80"
    probeTimeout: 5s       
    probeAttempt: 3
 
  nodeDrain:
    enabled: true
    
    nodeLabel: "agentpool=nodepool1"
    totalChaosDuration: 120
    
 
  networkLoss:
    enabled: true
    
    appLabel: "todos-api"
    appNamespace: microservices
    networkInterface: "eth0"
    lossPercentage: "50"       
    totalChaosDuration: 60
    
 

rbac:
 
  serviceAccountName: litmus-chaos-admin
 

audit:
 
  enabled: true
 

monitoring:
  serviceMonitor:
    enabled: false
    
    labels:
      release: monitoring
