apiVersion: v2
name: monitoring
description: Observability stack - Prometheus, Grafana, AlertManager, Loki, Fluent Bit
version: 0.1.0
type: application

dependencies:
    - name: prometheus
      version: "~26.0.0"
      repository: https://prometheus-community.github.io/helm-charts

    - name: grafana
      version: "~8.0.0"
      repository: https://grafana.github.io/helm-charts

    - name: loki
      version: "~6.28.0"
      repository: https://grafana.github.io/helm-charts

    - name: fluent-bit
      version: "~0.47.0"
      repository: https://fluent.github.io/helm-charts

    - name: tempo
      version: "~1.24.1"
      repository: https://grafana-community.github.io/helm-charts/
