gatewayClass:
  name: "nginx"
  kind: "GatewayClass"
  contollerName: "nginx.org/gateway-controller"


gateway:
  kind: "Gateway"
  name: "frontend-gateway"  
  namespaces: "nginx-gateway"
  listeners:
      name: "http"
      port: 80
      protocol: "HTTP"
      allowedRoutes:
        namespaces: "frontend"