httpRoute:
  kind: HTTPRoute
  metadata:
    name: http-route
    namespace: "frontend"
  nameParentRefs: "frontend-gateway"
  nameService: "frontend-frontend-svc"
  port: 80
  gatewayNamespace: "gateway-infra" 
