# Configuración global
global:
  namespace: microservices

# Configuración del ConfigMap
config:
  todoApiPort: "8082"
  redisHost: "microservices-redis-svc.microservices.svc.cluster.local"
  redisPort: "6379"
  redisChannel: "log_channel"

# Configuración de la imagen
image:
  repository: barcino/todos
  tag: "1.0.0"
  pullPolicy: IfNotPresent

# Configuración del servicio
service:
  type: ClusterIP
  port: 8082

# Recursos del contenedor
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

# Réplicas
replicaCount: 1

# HPA configuración
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Labels
labels:
  app: todos-api
