# Configuración global
global:
  namespace: microservices
replicaCount: 1

image:
  repository: redis
  tag: "7.4"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 6379
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# HPA configuración
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Labels
labels:
  app: redis
  component: cache
  tier: database

#Linkerd annotations
annotations:
    linkerd.io/inject: enabled

#ServiceProfile configuration for Linkerd
serviceProfile:
  timeout: 5s
  isRetryable: true
  pathRegex: ".*"
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s