apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.namespace }}-{{ .Chart.Name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.labels.app }}
data:
    PORT: {{ .Values.config.port | quote }}
    AUTH_API_ADDRESS: {{ .Values.config.authAddress | quote }}
    TODOS_API_ADDRESS: {{ .Values.config.todosAddress | quote }}