apiVersion: v1
kind: ConfigMap
metadata:
  # CAMBIO: Usamos Release.Name
  name: {{ printf "%s-%s-config" .Release.Name .Chart.Name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: {{ .Values.labels.app | quote }}
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}