---
# Deployment para Users API (Spring Boot/Java)
apiVersion: apps/v1
kind: Deployment
metadata:
  # CAMBIO: printf y quote
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: {{ .Values.labels.app | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app | quote }}
  template:
    metadata:
      annotations:
        {{- with .Values.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app: {{ .Values.labels.app | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        envFrom:
        - configMapRef:
            # CAMBIO: Mismo nombre del ConfigMap
            name: {{ printf "%s-%s-config" .Release.Name .Chart.Name | quote }}
        - secretRef:
            # CAMBIO: Mismo nombre del Secret
            name: {{ printf "%s-%s-secret" .Release.Name .Chart.Name | quote }}