apiVersion: v1
kind: Secret
metadata:
  # CAMBIO: Usamos Release.Name
  name: {{ printf "%s-%s-secret" .Release.Name .Chart.Name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
type: Opaque
data:
  JWT_SECRET: UFJGVA==