# Service para Users API
apiVersion: v1
kind: Service
metadata:
  # CAMBIO: Agregamos printf y quote
  name: {{ printf "%s-%s-svc" .Release.Name .Chart.Name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: {{ .Values.labels.app | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.labels.app | quote }}