name: Helm Chart Validation

on:
  push:
    paths:
      - 'helm/**'
  pull_request:
    paths:
      - 'helm/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Resolve Helm dependencies
        run: helm dependency update helm/

      - name: Lint Auth API
        run: helm lint helm/microservice/charts/auth-api

      - name: Lint Todos API
        run: helm lint helm/microservice/charts/todos-api

      - name: Lint Users API
        run: helm lint helm/microservice/charts/users-api

      - name: Lint Log Message Processor
        run: helm lint helm/microservice/charts/log-message-processor

      - name: Lint Redis
        run: helm lint helm/microservice/charts/redis

      - name: Lint Frontend
        run: helm lint helm/frontend

      - name: Lint Gateway Controller
        run: helm lint helm/gateway-controller

      - name: Lint Gateway Infra
        run: helm lint helm/gateway-infra

      - name: Lint Routes
        run: helm lint helm/routes

      - name: Lint chart raíz
        run: helm lint helm/

      - name: Dry Run completo
        run: |
          helm install --dry-run=client --debug test-release helm/ \
            --set global.namespace=microservices
