name: Helm Chart Validation

on:
  push:
    paths:
      - 'helm/**'
  pull_request:
    paths:
      - 'helm/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      # Lint microservices
      - name: Lint Auth API
        run: helm lint helm/microservice/charts/auth-api

      - name: Lint Todos API
        run: helm lint helm/microservice/charts/todos-api

      - name: Lint Users API
        run: helm lint helm/microservice/charts/users-api

      - name: Lint Log Message Processor
        run: helm lint helm/microservice/charts/log-message-processor

      - name: Lint Redis
        run: helm lint helm/microservice/charts/redis

      # Lint del frontend
      - name: Lint Frontend
        run: helm lint helm/frontend

      # Lint del gateway 
      - name: Lint Gateway Controller
        run: helm lint helm/gateway-controller

      - name: Lint Gateway Infra
        run: helm lint helm/gateway-infra

      # Dry Run 
      - name: Dry Run Microservicios
        run: |
          helm install --dry-run --debug test-microservice helm/microservice \
            --set global.namespace=microservices

      - name: Dry Run Frontend
        run: |
          helm install --dry-run --debug test-frontend helm/frontend \
            --set global.namespace=frontend

      - name: Dry Run Gateway Infra
        run: |
          helm install --dry-run --debug test-gateway helm/gateway-infra \
            --set global.namespace=gateway-infra