apiVersion: gateway.networking.k8s.io/v1
kind: {{ .Values.httpRoute.kind }}
metadata:
  name: {{ .Values.httpRoute.metadata.nameLinkerd }}
  namespace: {{ .Values.httpRoute.metadata.namespacesLinkerd }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.nameParentRefs }}
      namespace: {{ .Values.httpRoute.gatewayNamespace }}
  hostnames:
  - "linkerd.santiago.monster"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.httpRoute.nameServiceLinkerd }}
          port: {{ .Values.httpRoute.portLinkerd }}